name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Ganti dengan versi Node.js yang digunakan

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (opsional, jika ada)
      - name: Run tests
        run: npm test

      # Build the app (opsional, jika diperlukan)
      - name: Build app
        run: npm run build

      # Deploy (jika ingin melakukan deploy ke server atau layanan lain)
      - name: Deploy to Production
        run: |
          echo "Deploying to production server..."
          # Misalnya menggunakan Docker untuk deploy
          docker build -t my-web-app .
          docker run -d -p 3000:3000 my-web-app
